# -*- coding: utf-8 -*-
"""rock_paper_scissors.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fh-TyBYr_ZZpTXikfMBQeUIMNVXs3xkw
"""

import random

#function that will compute the arguments and check if they are in the expected range

def ask_user_for_int(prompt, low, high): #parameters
  while True:
    try:
      x = int(input(prompt))
      if x < low or x > high:
        print('Must be between', low, 'and', high)
      else:
        break
    except ValueError:
      print('Invalid value - try again')
  return x


#main part of our code..........

#create 3 string variables
tie = 'Its a tie'
win = 'Congrats, you won!'
lose = 'Sorry, you lost'

#ask how many rounds the user wants to play
num_times = ask_user_for_int('How many rounds do you want to play? ', 1, 5) #arguments

#these wil be used to count the user wins and the computer wins by rounds
user_wins = 0
computer_wins = 0


for x in range(num_times):

  print('Round #', x + 1, 'Start!')
  #call the function to ask the user for his choice
  user = ask_user_for_int('Enter 1, 2, 3 for Rock, Paper or Scissors: ', 1, 3) #arguments (its inside the for loop, so it will ask every round)

#print what the user chose (its inside the for loop, so it will print every round)

  if user == 1:
    print('You chose rock')
  elif user == 2:
    print('You chose paper')
  else:
    print('You chose scissors')

  #call radint() function from random module

  computer = random.randint(1, 3)

  # if statement to show what the computer chose

  if computer == 1:
    print('Computer chose rock')
  elif computer == 2:
    print('Computer chose paper')
  else:
    print('Computer chose scissors')

  # if statements to check who is the winner (the user or the computer)
  #prints one of the str variables that we created
  # sum the number of wins +1 if its a win

  if computer == user:
    print(tie)
  elif computer == 1 and user == 2:
    print(win)
    user_wins += 1
  elif computer == 1 and user == 3:
    print(lose)
    computer_wins += 1
  elif computer == 2 and user == 1:
    print(lose)
    computer_wins += 1
  elif computer == 2 and user == 3:
    print(win)
    user_wins += 1
  elif computer == 3 and user == 1:
    print(win)
    user_wins += 1
  else:
    print(lose)
    computer_wins += 1

# prints the wins of the user and the computer
print('Your wins:', user_wins)
print('Computer wins:', computer_wins)

# compare both user_wins and computer_wins to see who won the game
if(computer_wins > user_wins):
  print('Computer is the champion, you are a loser :( ')
elif(user_wins > computer_wins):
  print('You are the champion, Congrats!!!!! :) ')
else:
  print('You tied ;-;, I am sorry ')